# Generated by Django 6.0.2 on 2026-02-26 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('blocked', 'blocked')], default='active', max_length=20)),
            ],
            options={
                'db_table': 'admin_account',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='OrganizerAccount',
            fields=[
                ('organizer_account_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('blocked', 'blocked')], default='active', max_length=20)),
            ],
            options={
                'db_table': 'organizer_account',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hall_name', models.CharField(blank=True, max_length=255, null=True)),
                ('row_number', models.CharField(max_length=20)),
                ('seat_number', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'seat',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('blocked', 'blocked')], default='active', max_length=20)),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'venue',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('age_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cover_image_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('on_moderation', 'on_moderation'), ('published', 'published'), ('rejected', 'rejected'), ('archived', 'archived')], default='draft', max_length=20)),
                ('moderation_comment', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.category')),
                ('moderated_by_admin', models.ForeignKey(blank=True, db_column='moderated_by_admin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_events', to='core.adminaccount')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='EventSession',
            fields=[
                ('session_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.event')),
            ],
            options={
                'db_table': 'event_session',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('awaiting_payment', 'awaiting_payment'), ('paid', 'paid'), ('cancelled', 'cancelled'), ('refunded', 'refunded'), ('expired', 'expired')], default='awaiting_payment', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cart', models.OneToOneField(blank=True, db_column='cart_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='core.cart')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.useraccount')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrganizerProfile',
            fields=[
                ('organizer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('display_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('telegram', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('address_text', models.TextField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('about_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer_account', models.OneToOneField(db_column='organizer_account_id', on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to='core.organizeraccount')),
            ],
            options={
                'db_table': 'organizer_profile',
            },
        ),
        migrations.CreateModel(
            name='OrganizerDetails',
            fields=[
                ('legal_details_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('short_legal_name', models.CharField(max_length=255)),
                ('full_legal_name', models.CharField(max_length=512)),
                ('legal_address', models.TextField()),
                ('inn', models.CharField(max_length=12)),
                ('ogrn', models.CharField(blank=True, max_length=15, null=True)),
                ('kpp', models.CharField(blank=True, max_length=9, null=True)),
                ('org_type', models.CharField(choices=[('legal_entity', 'legal_entity'), ('ip', 'ip'), ('self_employed', 'self_employed'), ('individual', 'individual')], max_length=20)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('head_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('head_position', models.CharField(blank=True, max_length=255, null=True)),
                ('okved', models.CharField(blank=True, max_length=32, null=True)),
                ('okopf', models.CharField(blank=True, max_length=16, null=True)),
                ('opf_name', models.CharField(blank=True, max_length=255, null=True)),
                ('organizer', models.OneToOneField(db_column='organizer_id', on_delete=django.db.models.deletion.CASCADE, related_name='organizer_details', to='core.organizerprofile')),
            ],
            options={
                'db_table': 'organizer_details',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(db_column='organizer_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.organizerprofile'),
        ),
        migrations.CreateModel(
            name='OrganizerVerification',
            fields=[
                ('verification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_submitted', 'not_submitted'), ('submitted', 'submitted'), ('in_review', 'in_review'), ('approved', 'approved'), ('rejected', 'rejected')], default='not_submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('organizer', models.OneToOneField(db_column='organizer_id', on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='core.organizerprofile')),
                ('reviewed_by_admin', models.ForeignKey(blank=True, db_column='reviewed_by_admin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to='core.adminaccount')),
            ],
            options={
                'db_table': 'organizer_verification',
            },
        ),
        migrations.CreateModel(
            name='OrganizerDocument',
            fields=[
                ('document_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('inn_certificate', 'inn_certificate'), ('head_appointment_order', 'head_appointment_order'), ('other', 'other')], max_length=64)),
                ('file_url', models.URLField()),
                ('verification', models.ForeignKey(db_column='verification_id', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.organizerverification')),
            ],
            options={
                'db_table': 'organizer_document',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.order')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('refund_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('requested', 'requested'), ('approved', 'approved'), ('processing', 'processing'), ('succeeded', 'succeeded'), ('rejected', 'rejected')], default='requested', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='core.order')),
            ],
            options={
                'db_table': 'refund',
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('ticket_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('qty_total', models.PositiveIntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='core.eventsession')),
            ],
            options={
                'db_table': 'ticket_type',
            },
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('reservation_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reservation', models.ForeignKey(db_column='reservation_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.reservation')),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='reservation_items', to='core.eventsession')),
                ('seat', models.ForeignKey(blank=True, db_column='seat_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_items', to='core.seat')),
                ('ticket_type', models.ForeignKey(db_column='ticket_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='reservation_items', to='core.tickettype')),
            ],
            options={
                'db_table': 'reservation_item',
            },
        ),
        migrations.CreateModel(
            name='OrderTicket',
            fields=[
                ('order_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='order_tickets', to='core.order')),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='order_tickets', to='core.eventsession')),
                ('seat', models.ForeignKey(blank=True, db_column='seat_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_tickets', to='core.seat')),
                ('ticket_type', models.ForeignKey(db_column='ticket_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='order_tickets', to='core.tickettype')),
            ],
            options={
                'db_table': 'order_ticket',
            },
        ),
        migrations.CreateModel(
            name='CartTicket',
            fields=[
                ('cart_tickets_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('cart', models.ForeignKey(db_column='cart_id', on_delete=django.db.models.deletion.CASCADE, related_name='cart_tickets', to='core.cart')),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='cart_tickets', to='core.eventsession')),
                ('seat', models.ForeignKey(blank=True, db_column='seat_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_tickets', to='core.seat')),
                ('ticket_type', models.ForeignKey(db_column='ticket_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='cart_tickets', to='core.tickettype')),
            ],
            options={
                'db_table': 'cart_tickets',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.useraccount'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='core.useraccount'),
        ),
        migrations.CreateModel(
            name='UserPaymentMethod',
            fields=[
                ('payment_method_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider_method_id', models.CharField(max_length=255)),
                ('card_last4', models.CharField(blank=True, max_length=4, null=True)),
                ('card_brand', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('disabled', 'disabled')], default='active', max_length=20)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='core.useraccount')),
            ],
            options={
                'db_table': 'user_payment_method',
            },
        ),
        migrations.AddField(
            model_name='seat',
            name='venue',
            field=models.ForeignKey(db_column='venue_id', on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='core.venue'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(db_column='venue_id', on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.venue'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core.event')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='core.useraccount')),
            ],
            options={
                'db_table': 'favorite',
                'constraints': [models.UniqueConstraint(fields=('user', 'event'), name='uq_favorite_user_event')],
            },
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('venue', 'hall_name', 'row_number', 'seat_number'), name='uq_seat_per_hall'),
        ),
    ]
